version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    env_file:
      - .env.backend    # your backend-specific env
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env.development  # your frontend dev env
  # …other services…
